version: '3.8'
networks:
  webapp:
    driver: bridge
secrets:
  pg-secret:
    file: {{ webapp_root_dir }}/config/pg_secret
  pg-user:
    file: {{ webapp_root_dir }}/config/pg_user
services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx_webapp
    volumes:
    - {{ webapp_root_dir }}/config/webapp-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webapp
    ports:
      - {{ webapp_host_port }}:80
    depends_on:
      - webapp
  webapp:
    image: {{ webapp_image_name }}:{{ webapp_image_version }}
    container_name: webapp
    environment:
      - DBHOST=webapp-postgres
      - DB=monitoringdb
    networks:
      - webapp
    secrets:
      - pg-secret
      - pg-user
    depends_on:
      webapp-postgres:
        condition: service_healthy
  webapp-postgres:
    image: postgres:15-alpine
    container_name: webapp_postgres
    volumes:
      - {{ webapp_root_dir }}/data/webapp-postgres:/var/lib/postgresql/data
      - {{ webapp_root_dir }}/config/init-table.sql:/docker-entrypoint-initdb.d/init-table.sql
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-secret
      - POSTGRES_USER_FILE=/run/secrets/pg-user
      - POSTGRES_DB=monitoringdb
    networks:
      - webapp
    secrets:
      - pg-secret
      - pg-user
    healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "monitoringdb"]
        interval: 10s
        timeout: 30s
        retries: 5
        start_period: 15s