# # config file version
apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   uid: prometheus
   access: direct
   url: http://prometheus:9090
   isDefault: true
   version: 1
   editable: true
