version: '3.9'
networks:
  webapp:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    container_name: nginx_webapp
    volumes:
    - ./config/webapp-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webapp
    ports:
      - 8080:80
  webapp:
    image: webapp:v5
    container_name: webapp
    environment:
      - DBHOST=''
      - DB=''
      - DBUSER=''
      - DBPASS=''
    networks:
      - webapp
  postgres:
    image: postgres:15-alpine
    container_name: webapp_postgres
    volumes:
      - /home/teele/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=''
      - POSTGRES_USER=''
      - POSTGRES_DB=''
    networks:
      - webapp
  