global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']
