version: '3.9'
volumes:
  prometheus-testing:
    driver: local
  grafana-testing:
    driver: local
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-testing:/prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-testing:/var/lib/grafana
      - ./config/grafana/alerting/demo-alerts.yaml:/etc/grafana/provisioning/alerting/deo-alerts.yaml
      - ./config/grafana/datasources/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  demo_nginx:
    image: nginx:latest
    container_name: demo_nginx
    volumes:
    - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: '-nginx.scrape-uri http://demo_nginx:80/metrics'